version: 2.1

jobs:
  test-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    environment:
      ENV_FILE: ci/deps/circle-37-arm64.yaml
      PYTEST_WORKERS: auto
      PATTERN: "not slow and not network and not clipboard and not arm_slow"
    steps:
      - run: echo "CircleCI is working"

workflows:
  test:
    jobs:
      - test-arm
